I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 228, in script
    with Fade(1.5)           # Transition
TypeError: Fade() missing 2 required positional arguments: 'hold_time' and 'in_time'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 228, in script
    with Fade(1.5)           # Transition
  File "H:\Programs\RenPy\renpy\ast.py", line 1374, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "H:\Programs\RenPy\renpy\exports\statementexports.py", line 257, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "H:\Programs\RenPy\renpy\display\core.py", line 1581, in do_with
    return self.interact(trans_pause=True,
  File "H:\Programs\RenPy\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "H:\Programs\RenPy\renpy\display\core.py", line 2669, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "H:\Programs\RenPy\renpy\display\core.py", line 2578, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: Fade() missing 2 required positional arguments: 'hold_time' and 'in_time'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
Escape from the Carnival of Horrors 1.0
Tue Jun 17 02:37:38 2025
